namespace:
  name: prod
 
service:
  port: 7111

image:
  pullPolicy: Always
  # Standout Suggestion 2: Push Docker images with custom tags (uncomment the following 'v1.3', comment the 'latest')
  #tag: v1.3
  tag: latest

replicaCount: 5

resources:
  requests:
    memory: 128Mi
    cpu: 350m
  limits:
    memory: 256Mi
    cpu: 500m

